[template]
src = "kubernetes.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
prefix = "/registry/services"
keys = [
    "/specs/default",
    "/endpoints/default"
]

check_cmd = "nginx -t -c {{.src}}"
reload_cmd = "nginx -s reload"
